Sprint 2
IvanB56/middle.messenger.praktikum.yandex pull request #3
Opened 2022-12-26 12:08 UTC by IvanB56

2022-12-26 12:59 UTC, podlovchenko requested changes
Привет, перед тем как приступать к выполнению задания следующего спринта необходимо смержить зачтенный пулл реквест предыдущего (с 1 спринтом уже ничего не нужно делать, но перед тем как начинать делать задание 3 спринта нужно будет влить ветку sprint_2 в ветку main)
Файлов .css дублирующих .less не должно быть в репозитории
Локально и на пулл реквест проект не собирается
<img width="827" alt="Снимок экрана 2022-12-26 в 15 57 12" src="https://user-images.githubusercontent.com/22602747/209551619-85baf5f1-da1a-4e4a-9512-5dd87c053091.png">

2022-12-26 12:59 UTC, podlovchenko commented on package.json
> +    "components": "0.1.0",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express, nanoid)

2022-12-26 12:59 UTC, podlovchenko commented on src/components/UI/button/button.css
> +/* stylelint-enable no-empty-source, at-rule-no-unknown */
Для чего?

2022-12-26 12:59 UTC, podlovchenko commented on src/components/UI/button/button.ts
> +export class Button extends Block<object> {
```suggestion
export class Button extends Block<ButtonProps> {
```

2022-12-26 12:59 UTC, podlovchenko commented on src/components/UI/button/index.ts
> +export { Button as default } from "./button";
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2022-12-26 12:59 UTC, podlovchenko commented on src/components/UI/link/link.ts
> +    [key: string]: string;
Не очень информативный тип, стоит указать, что можно передавать такие параметры как text и href

2022-12-26 12:59 UTC, podlovchenko commented on src/components/chatMessages/chatMessages.less
> +  input[type="file"] {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Block.ts
> +    _registerEvents(eventBus: EventBus<Events>) {
Для приватных методов не хватает модификатора private

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Fetch.ts
> +enum METHODS {
enum обычно именуется в формате PascalCase

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Fetch.ts
> +    request(url: string | URL, options: RequestOptions & {method: string}, timeout = 5000): Promise<XMLHttpRequest> {
Есть же тип options

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Fetch.ts
> +    delete(url: string | URL, options: Options = {method: METHODS.DELETE}) {
Метод ниже передается, здесь излишне
```suggestion
    delete(url: string | URL, options: Options = {}) {
```

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Validation.ts
> +        if (["first_name", "second_name", "username"].indexOf((this.element as HTMLInputElement).name) !== -1) {
Есть метод includes

2022-12-26 12:59 UTC, podlovchenko commented on src/core/Validation.ts
> +        }
Для такого кейса хорошо подойдет конструкция switch case

2022-12-26 12:59 UTC, podlovchenko commented on tsconfig.json
> +  }
По заданию должны быть следующие настройки
```
"noImplicitAny": true,

"noUnusedLocals": true,

"noUnusedParameters": true,

"sourceMap": true,

"strictNullChecks": true
```

2022-12-27 15:24 UTC, podlovchenko commented
Привет, при переходе по ссылками `Cannot GET /registration`
Нужно добавить в server.js
```
app.get('*', function(req, res) {
    res.sendFile(path.join(__dirname, '/dist/index.html'));
});
```

2022-12-28 13:20 UTC, podlovchenko commented
Привет, перед сдачей работы прикрепи, пожалуйста, актуальную ссылку на нетлифай на последнюю версию приложения
Сейчас ссылка не открывается
Во остальном все окей, но если что есть еще одна итерация на проверку

2022-12-28 21:19 UTC, IvanB56 commented
На всякий случай продублирую ссылку на Netlfy тут: https://cerulean-dodol-4ea8e0.netlify.app/login

2022-12-29 10:32 UTC, podlovchenko commented
Привет, перепроверь, пожалуйста, регулярки в соответствии с заданием
<img width="749" alt="Снимок экрана 2022-12-29 в 13 28 06" src="https://user-images.githubusercontent.com/22602747/209938871-74cdd21d-552d-4c31-b845-40fa7892ccf4.png">
Сейчас в логине проходят спецсимволы, хотя по заданию не должны
<img width="524" alt="Снимок экрана 2022-12-29 в 13 32 09" src="https://user-images.githubusercontent.com/22602747/209938983-07a3511e-c823-400b-86c6-a032c45a2199.png">
В остальном все окей

2022-12-29 13:38 UTC, IvanB56 commented
Изменил регулярку для проверки символов на форме. Остальные поля нужно менять или достаточно такого поведения? И как сдать проект, у меня 3 попытки потрачены

2022-12-30 07:53 UTC, podlovchenko commented
Достаточно, спасибо за оперативные правки, работу принимаю)

2022-12-30 09:08 UTC, merged